name: 'Merge command'

on: issue_comment

jobs:
  merge-command:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Merge command
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_TO_MERGE=env-qa
        HEAD_BRANCH=env-prod

        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY.git
 
        git config --global user.name "fast-forward job"
        git config --global user.email "actions@github.com"
        git fetch origin $BRANCH_TO_MERGE
        git checkout -b $BRANCH_TO_MERGE origin/$BRANCH_TO_MERGE
        
        git fetch origin $HEAD_BRANCH
        git checkout -b $HEAD_BRANCH origin/$HEAD_BRANCH

        git merge --ff-only env-qa
        git push origin env-prod
